### ISSUE TITLE
Cannot apply Deepseek

### ISSUE THREAD

**Issue by Aegis1863** [Ciciella/AIcoder#3]
I don't know if there is something wrong, or it just doesn't support deepseek?
![image](https://github.com/user-attachments/assets/6082101c-cc42-4fb2-aa5c-7c08f2b9f930)
![image](https://github.com/user-attachments/assets/d6c826a0-59d7-45f1-9475-75f59cfb8c64)

**Comment by Ciciella** [comment]
模型id填错了,应该是"deepseek-chat"

**Comment by Bowen1911** [comment]
> 模型id填错了,应该是"deepseek-chat"

修改后没问题了，感谢
