### ISSUE TITLE
版本升级后，按钮变成了乱码

### ISSUE THREAD

**Issue by qlxmy** [Ciciella/AIcoder#6]
目前的版本是：v2.2.3
底下的执行按钮都变成了乱码，之前的版本并没有这个问题：
![1d09b7fbd9893b0d6b381b4b1051e51](https://github.com/user-attachments/assets/35c5b596-e222-43e2-9a20-4e0d67dcb928)

**Comment by Ciciella** [comment]
好的 我将在今天晚上修复他



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月19日(周四) 中午11:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Ciciella/AIcoder] 版本升级后，按钮变成了乱码 (Issue #6)




 
目前的版本是：v2.2.3
 底下的执行按钮都变成了乱码，之前的版本并没有这个问题：
 1d09b7fbd9893b0d6b381b4b1051e51.png (view on web)
